/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Logica.Livro;
import java.util.LinkedList;

/**
 *
 * @author mateus
 */
public class InterfaceLivro extends javax.swing.JFrame {
 LinkedList List = new LinkedList();
    /**
     * Creates new form InterfaceLivro
     */
    public InterfaceLivro() {
        initComponents();
    }
    public void ListarLivros(){
      
          Object[] TodosLivros = List.toArray();
          for(int i=0; i<TodosLivros.length; i++){
              if(TodosLivros[i] instanceof Livro){
                   Livro li = (Livro) TodosLivros[i];
              
              panelLivros.setText(li.toString()+ "\n");
              }
             
          }
      
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlistar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelLivros = new javax.swing.JTextArea();
        txtAnoPub = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEditor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnexcluirano = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        btnlistar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnlistar.setText("LISTAR LIVROS");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar);
        btnlistar.setBounds(23, 280, 190, 31);

        panelLivros.setColumns(20);
        panelLivros.setRows(5);
        jScrollPane1.setViewportView(panelLivros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(226, 271, 411, 135);
        getContentPane().add(txtAnoPub);
        txtAnoPub.setBounds(380, 50, 100, 30);
        getContentPane().add(txtAutor);
        txtAutor.setBounds(140, 50, 100, 30);
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(10, 50, 100, 30);
        getContentPane().add(txtEditor);
        txtEditor.setBounds(260, 50, 100, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ano de Publicação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 30, 120, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Autor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 30, 40, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Titutlo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 30, 50, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Editora");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 30, 60, 17);

        btnCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCadastrar.setText("CADASTRAR LIVRO");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(160, 100, 220, 30);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnExcluir.setText("EXCLUIR LIVRO");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(23, 340, 190, 31);

        btnexcluirano.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnexcluirano.setText("EXCLUSÃO (2002)");
        btnexcluirano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluiranoActionPerformed(evt);
            }
        });
        getContentPane().add(btnexcluirano);
        btnexcluirano.setBounds(23, 390, 190, 31);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        ListarLivros();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Livro li = new Livro(txtTitulo.getText(), txtAutor.getText(), txtEditor.getText(), Integer.parseInt(txtAnoPub.getText()));
        
        if(List.peekFirst()==null){
            List.addFirst(li);
        }
        else{
            List.addLast(li);
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        panelLivros.setText("");
        Livro li = (Livro) List.removeFirst();
        panelLivros.setText(li.toString());
      
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnexcluiranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluiranoActionPerformed
        // TODO add your handling code here:
        Object[] TodosLivros = List.toArray();
          for(int i=0; i<TodosLivros.length; i++){
              Livro li = (Livro) TodosLivros[i];
              if(li.getAnoPublicacao()>2002){
                  List.addLast(li);
              }
    }//GEN-LAST:event_btnexcluiranoActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnexcluirano;
    private javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea panelLivros;
    private javax.swing.JTextField txtAnoPub;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
