
package Interfaces;



import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.dao.AlunoDAO;


public class JframePrincipal extends javax.swing.JFrame {
    
    
  
   
    /**
     * Creates new form JframePrincipal
     */
    public JframePrincipal() {
        initComponents();
        indexJtable();
       
    
         
        
    }
   
    public void indexJtable(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaAluno.getModel();
        modelo.setNumRows(0);
        AlunoDAO aludao = new AlunoDAO();
        
        for(Aluno a: aludao.index()){
            modelo.addRow(new Object[]{
            a.getRgm(),
            a.getNome(),
            a.getIdade(),
            a.getCurso()
            
            });
           
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInseir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidade = new javax.swing.JTextField();
        txtrgm = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        btninserir = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnapagar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        panelInseir.setLayout(null);

        jLabel1.setText("RGM:");
        panelInseir.add(jLabel1);
        jLabel1.setBounds(154, 21, 26, 14);

        jLabel2.setText("Nome:");
        panelInseir.add(jLabel2);
        jLabel2.setBounds(149, 62, 31, 14);

        jLabel3.setText("Idade:");
        panelInseir.add(jLabel3);
        jLabel3.setBounds(149, 97, 32, 14);

        jLabel4.setText("Curso:");
        panelInseir.add(jLabel4);
        jLabel4.setBounds(149, 135, 32, 14);
        panelInseir.add(txtidade);
        txtidade.setBounds(199, 94, 79, 20);
        panelInseir.add(txtrgm);
        txtrgm.setBounds(198, 18, 80, 20);
        panelInseir.add(txtnome);
        txtnome.setBounds(198, 56, 80, 20);
        panelInseir.add(txtcurso);
        txtcurso.setBounds(199, 132, 79, 20);

        btninserir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btninserir.setText("Inserir");
        btninserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninserirActionPerformed(evt);
            }
        });
        panelInseir.add(btninserir);
        btninserir.setBounds(10, 20, 120, 31);

        btnlistar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnlistar.setText("Listar");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        panelInseir.add(btnlistar);
        btnlistar.setBounds(20, 460, 77, 31);

        btneditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        panelInseir.add(btneditar);
        btneditar.setBounds(10, 61, 121, 31);

        btnapagar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnapagar.setText("Apagar");
        btnapagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapagarActionPerformed(evt);
            }
        });
        panelInseir.add(btnapagar);
        btnapagar.setBounds(10, 103, 121, 31);

        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RGM", "NOME", "IDADE", "CURSO"
            }
        ));
        jScrollPane2.setViewportView(tabelaAluno);

        panelInseir.add(jScrollPane2);
        jScrollPane2.setBounds(170, 180, 452, 402);

        getContentPane().add(panelInseir);
        panelInseir.setBounds(0, 0, 780, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
         indexJtable();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btninserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninserirActionPerformed
         // TODO add your handling code here:
        
        Aluno a = new Aluno();
        AlunoDAO dao = new AlunoDAO();
        
        a.setRgm(txtrgm.getText());
        a.setNome(txtnome.getText());
        a.setIdade(Integer.parseInt(txtidade.getText()));
        a.setCurso(txtcurso.getText());
        dao.create(a);
        indexJtable();
        
    }//GEN-LAST:event_btninserirActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        Aluno a = new Aluno();
        AlunoDAO dao = new AlunoDAO();
        
        a.setRgm(txtrgm.getText());
        a.setNome(txtnome.getText());
        a.setIdade(Integer.parseInt(txtidade.getText()));
        a.setCurso(txtcurso.getText());
       a.setRgm(txtrgm.getText());
        dao.update(a);
        indexJtable();
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnapagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapagarActionPerformed
        // TODO add your handling code here:
         Aluno a = new Aluno();
        AlunoDAO dao = new AlunoDAO();
        a.setRgm(txtrgm.getText());
        dao.delete(a);
        indexJtable();
    }//GEN-LAST:event_btnapagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapagar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btninserir;
    private javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelInseir;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtidade;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtrgm;
    // End of variables declaration//GEN-END:variables
}
